## Customer Shopping Behavior Analysis for Business Insights

### Problem Statement:

- A retail business wants to better understand its customers' purchasing behavior to improve sales, optimize marketing strategies, and enhance customer satisfaction. The company has collected transactional and behavioral data, but lacks clear insights.

- The goal of this project is to analyze customer shopping data to identify patterns, trends, and factors that influence purchasing decisions.

### importing libraries

In [49]:
import pandas as pd
import numpy as np

### Loading dataset

In [50]:
df = pd.read_csv("customer_shopping_behavior.csv")

### Basic data Overview

In [51]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,913,24,Male,Hoodie,Clothing,56.0,Arkansas,M,Green,Winter,3.4,Yes,Next Day Air,Yes,32.0,Bank Transfer,Monthly
5046,3466,19,Female,Backpack,Accessories,53.0,Iowa,M,Gold,Spring,3.4,No,Standard,No,31.0,Debit Card,Weekly
5047,3572,70,Female,Skirt,Clothing,27.0,North Dakota,M,White,Summer,3.2,No,Standard,No,15.0,Bank Transfer,Every 3 Months
5048,3195,43,Female,Sneakers,Footwear,52.0,Maryland,L,Gold,Summer,4.6,No,Standard,No,10.0,Credit Card,Bi-Weekly
5049,1832,62,Male,Blouse,Clothing,71.0,Maine,M,Cyan,Summer,3.3,No,Free Shipping,No,5.0,Bank Transfer,Every 3 Months

In [52]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [53]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
5045,913,24,Male,Hoodie,Clothing,56.0,Arkansas,M,Green,Winter,3.4,Yes,Next Day Air,Yes,32.0,Bank Transfer,Monthly
5046,3466,19,Female,Backpack,Accessories,53.0,Iowa,M,Gold,Spring,3.4,No,Standard,No,31.0,Debit Card,Weekly
5047,3572,70,Female,Skirt,Clothing,27.0,North Dakota,M,White,Summer,3.2,No,Standard,No,15.0,Bank Transfer,Every 3 Months
5048,3195,43,Female,Sneakers,Footwear,52.0,Maryland,L,Gold,Summer,4.6,No,Standard,No,10.0,Credit Card,Bi-Weekly
5049,1832,62,Male,Blouse,Clothing,71.0,Maine,M,Cyan,Summer,3.3,No,Free Shipping,No,5.0,Bank Transfer,Every 3 Months

In [54]:
df.sample(7)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
4296,2470,68,Male,Sandals,Footwear,92.00,Maryland,M,Yellow,Fall,5.0,No,Standard,No,27.0,PayPal,Annually
2391,3397,29,Female,Pants,Clothing,37.00,Tennessee,XL,Black,Winter,5.0,No,Next Day Air,No,5.0,PayPal,Quarterly
199,641,53,Male,Skirt,Clothing,88.00,Minnesota,M,Gray,Summer,4.4,Yes,Store Pickup,Yes,28.0,Debit Card,Fortnightly
3441,3858,42,Female,Hat,Accessories,21.00,Texas,S,Yellow,Summer,3.1,No,Store Pickup,No,29.0,Credit Card,Every 3 Months
2899,2467,32,Male,Shorts,Clothing,84.00,South Dakota,S,Pink,Summer,3.7,No,Express,No,37.0,Cash,Annually
4354,1969,67,Male,Shirt,Clothing,70.00,Minnesota,S,Blue,Spring,4.2,No,Standard,No,25.0,Credit Card,Weekly
3785,4988,46,Other,Shirt,Accessories,1164.11,Los Angeles,S,Green,Autumn,NaN,Yes,Express,No,NaN,PayPal,Monthly

### Shape of data

In [55]:
df.shape

(5050, 17)

### column names

In [56]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='object')

### data info

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Item Purchased          5050 non-null   object
 4   Category                5050 non-null   object
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5050 non-null   object
 9   Season                  5050 non-null   object
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   object
 12  Shipping Type           5050 non-null   object
 13  Discount Applied        5050 non-null   object
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   object
 16  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 670.8+ KB

### Checking  null values

In [58]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

### Checking Duplicates

In [59]:
df.duplicated().sum()

50

### Statistical Summary

In [60]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,5050.000000,5050.000000,4494.000000,4449.000000,4502.000000
mean,2519.570891,44.150495,144.765236,3.668195,25.221901
std,1470.402964,15.282328,275.590101,0.865357,14.521635
min,1.000000,18.000000,10.120000,1.000000,0.000000
25%,1252.250000,31.000000,41.000000,3.000000,13.000000
50%,2499.500000,44.000000,65.000000,3.700000,25.000000
75%,3740.750000,57.000000,89.000000,4.400000,38.000000
max,5099.000000,70.000000,1499.760000,5.000000,50.000000

### Understand Each Column

In [61]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [62]:
df['Age'].unique()

array([22, 51, 18, 40, 23, 62, 61, 37, 42, 35, 46, 64, 57, 68, 56, 52, 30,
       21, 70, 58, 33, 60, 41, 34, 66, 38, 49, 69, 67, 24, 65, 43, 39, 59,
       53, 47, 36, 20, 44, 55, 26, 29, 50, 19, 27, 48, 45, 63, 25, 31, 28,
       32, 54], dtype=int64)

In [63]:
df['Age'].value_counts()

Age
41    114
57    111
69    110
54    109
25    107
46    104
28    104
59    104
49    104
23    104
27    103
29    103
42    102
31    101
66    101
62    100
65    100
32    100
50    100
58     98
63     98
19     98
53     97
56     96
37     96
60     96
55     95
43     94
20     94
70     94
40     93
68     93
36     92
38     91
18     91
52     91
47     91
35     90
34     90
51     89
45     89
64     89
22     88
39     87
61     87
26     86
24     86
48     85
33     84
30     84
21     83
44     79
67     75
Name: count, dtype: int64

In [64]:
df['Age'].describe()

count    5050.000000
mean       44.150495
std        15.282328
min        18.000000
25%        31.000000
50%        44.000000
75%        57.000000
max        70.000000
Name: Age, dtype: float64

In [65]:
df['Gender'].value_counts()

Gender
Male      3018
Female    1670
Other      362
Name: count, dtype: int64

In [66]:
df['Category'].value_counts()

Category
Clothing       2130
Accessories    1615
Footwear        607
Electronics     370
Outerwear       328
Name: count, dtype: int64

In [67]:
df['Purchase Amount (USD)'].describe()

count    4494.000000
mean      144.765236
std       275.590101
min        10.120000
25%        41.000000
50%        65.000000
75%        89.000000
max      1499.760000
Name: Purchase Amount (USD), dtype: float64

In [68]:
df['Discount Applied'].value_counts()

Discount Applied
No     2789
Yes    2261
Name: count, dtype: int64

In [69]:
df['Review Rating'].describe()

count    4449.000000
mean        3.668195
std         0.865357
min         1.000000
25%         3.000000
50%         3.700000
75%         4.400000
max         5.000000
Name: Review Rating, dtype: float64

In [70]:
df['Frequency of Purchases'].value_counts()

Frequency of Purchases
Monthly           946
Quarterly         933
Weekly            894
Every 3 Months    592
Annually          581
Bi-Weekly         556
Fortnightly       548
Name: count, dtype: int64